import { getCurrentAdminProfile } from '@/lib/auth'
import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'
import { sql } from '@/lib/neon'
import { appointmentStatus } from '@/lib/clinic'
import { SubmitButton } from '../_components/submit-button'
import { FormFeedback } from '../_components/form-feedback'

async function save(formData: FormData) { 'use server'
  try {
    const patient_id = String(formData.get('patient_id')||''); const appointment_date = String(formData.get('appointment_date')||''); const start_time = String(formData.get('start_time')||''); const end_time = String(formData.get('end_time')||'')
    if (!patient_id || !appointment_date || !start_time || !end_time) redirect('/admin/agenda?error=Verifique+os+campos+obrigat%C3%B3rios')
    await sql`insert into appointments (patient_id, professional_id, procedure_id, notes, appointment_date, start_time, end_time, status) values (${patient_id}::uuid, ${String(formData.get('professional_id')||'')||null}::uuid, ${String(formData.get('procedure_id')||'')||null}::uuid, ${String(formData.get('notes')||'')||null}, ${appointment_date}, ${start_time}, ${end_time}, ${String(formData.get('status')||'scheduled')}::appointment_status)`
    revalidatePath('/admin/agenda'); redirect('/admin/agenda?ok=Agendamento+criado+com+sucesso')
  } catch (e) { console.error('agenda.save', e); redirect('/admin/agenda?error=N%C3%A3o+foi+poss%C3%ADvel+salvar.+Verifique+os+dados+e+tente+novamente') }
}
export default async function Page({ searchParams }: { searchParams?: Promise<Record<string,string>> }) { const admin = await getCurrentAdminProfile(); if(!admin) redirect('/admin'); const params=(await searchParams)??{}; const [rows, patients, professionals, procedures] = await Promise.all([sql`select a.*, p.full_name as patient_name from appointments a join patients p on p.id=a.patient_id order by appointment_date desc, start_time desc limit 100`,sql`select id, full_name from patients order by full_name`,sql`select id, full_name from professionals where is_active=true order by full_name`,sql`select id, name from procedures where is_active=true order by name`]); return <section className='space-y-4'><h1 className='text-2xl font-bold'>Agendamentos</h1><FormFeedback ok={params.ok} error={params.error} /><form action={save} className='grid md:grid-cols-2 gap-3'><select name='patient_id' required><option value=''>patient_id *</option>{(patients as any[]).map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select><select name='professional_id'><option value=''>professional_id</option>{(professionals as any[]).map(p=><option key={p.id} value={p.id}>{p.full_name}</option>)}</select><select name='procedure_id'><option value=''>procedure_id</option>{(procedures as any[]).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select name='status'>{appointmentStatus.map(s=><option key={s} value={s}>{s}</option>)}</select><input name='appointment_date' type='date' required /><input name='start_time' type='time' required /><input name='end_time' type='time' required /><textarea name='notes' className='md:col-span-2' placeholder='notes' /><SubmitButton /></form><div className='overflow-auto'><table className='w-full text-sm'><thead><tr><th>Paciente</th><th>Data</th><th>Status</th></tr></thead><tbody>{(rows as any[]).map(r=><tr key={r.id}><td>{r.patient_name}</td><td>{r.appointment_date} {r.start_time}</td><td>{r.status}</td></tr>)}</tbody></table></div></section> }
