import { getCurrentAdminProfile } from '@/lib/auth'
import { sql } from '@/lib/neon'
import { redirect } from 'next/navigation'
import { revalidatePath } from 'next/cache'
import { SubmitButton } from '../_components/submit-button'
import { FormFeedback } from '../_components/form-feedback'
const parseMoney = (v: string) => Number(v.replace(/\./g, '').replace(',', '.')) || 0
async function saveBudgetItem(formData: FormData) { 'use server'
  try { const budget_id = String(formData.get('budget_id') || ''); const description = String(formData.get('description') || '').trim(); const quantity = Number(formData.get('quantity') || 1); const unit_amount = parseMoney(String(formData.get('unit_amount') || '0')); if (!budget_id || !description) redirect('/admin/budget-items?error=Verifique+os+campos+obrigat%C3%B3rios'); await sql`insert into budget_items (budget_id, procedure_id, description, quantity, unit_amount) values (${budget_id}::uuid, ${String(formData.get('procedure_id') || '') || null}::uuid, ${description}, ${Number.isFinite(quantity) && quantity > 0 ? quantity : 1}, ${unit_amount})`; revalidatePath('/admin/budget-items'); revalidatePath('/admin/budgets'); redirect('/admin/budget-items?ok=Item+de+or%C3%A7amento+salvo+com+sucesso') } catch (e) { console.error('budget_items.save', e); redirect('/admin/budget-items?error=N%C3%A3o+foi+poss%C3%ADvel+salvar.+Verifique+os+dados+e+tente+novamente') }
}
export default async function Page({ searchParams }: { searchParams?: Promise<Record<string,string>> }) { const admin = await getCurrentAdminProfile(); if (!admin) redirect('/admin'); const params=(await searchParams)??{}; const [budgetItems, budgets, procedures] = await Promise.all([sql`select bi.*, b.patient_id, p.full_name as patient_name, pr.name as procedure_name from budget_items bi join budgets b on b.id = bi.budget_id join patients p on p.id = b.patient_id left join procedures pr on pr.id = bi.procedure_id order by bi.created_at desc limit 100`,sql`select b.id, p.full_name as patient_name, b.status from budgets b join patients p on p.id = b.patient_id order by b.created_at desc limit 200`,sql`select id, name from procedures where is_active = true order by name`]); return <section className='space-y-4'><h1 className='text-2xl font-bold'>Itens do Orçamento</h1><FormFeedback ok={params.ok} error={params.error} /><form action={saveBudgetItem} className='grid md:grid-cols-2 gap-3'><select name='budget_id' required><option value=''>budget_id *</option>{(budgets as any[]).map(b => <option key={b.id} value={b.id}>{b.id.slice(0, 8)} - {b.patient_name} ({b.status})</option>)}</select><select name='procedure_id'><option value=''>procedure_id</option>{(procedures as any[]).map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><input name='description' required placeholder='description *' /><input name='quantity' type='number' min={1} defaultValue={1} required /><input name='unit_amount' required placeholder='unit_amount ex: 120,00' /><SubmitButton label='Salvar item' /></form><div className='overflow-auto'><table className='w-full text-sm'><thead><tr><th>Paciente</th><th>Descrição</th><th>Procedimento</th><th>Qtd.</th><th>Unitário</th><th>Total</th></tr></thead><tbody>{(budgetItems as any[]).map(item => <tr key={item.id}><td>{item.patient_name}</td><td>{item.description}</td><td>{item.procedure_name || '-'}</td><td>{item.quantity}</td><td>{Number(item.unit_amount).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</td><td>{Number(item.line_total).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' })}</td></tr>)}</tbody></table></div></section> }
